ignoreDifferences:
  - group: ""
    kind: Secret
    name: chaos-mesh-chaosd-client-certs
    jsonPointers:
      - /data
  - group: ""
    kind: Secret
    name: chaos-mesh-daemon-certs
    jsonPointers:
      - /data
  - group: ""
    kind: Secret
    name: chaos-mesh-daemon-client-certs
    jsonPointers:
      - /data
  - group: ""
    kind: Secret
    name: chaos-mesh-webhook-certs
    jsonPointers:
      - /data
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
      - .webhooks[].clientConfig.caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
      - .webhooks[].clientConfig.caBundle
  - group: apps
    kind: DaemonSet
    jqPathExpressions:
      - .spec.template.metadata.annotations.rollme
  - group: apps
    kind: Deployment
    jqPathExpressions:
      - .spec.template.metadata.annotations.rollme
syncPolicy:
  automated:
    enabled: false
