repositories:
- name: chaos-mesh
  url: https://charts.chaos-mesh.org

releases:
- name: chaos-mesh
  namespace: chaos-mesh
  createNamespace: true
  chart: chaos-mesh/chaos-mesh
  version: 2.8.3
  values:
  - dashboard:
      ingress:
        apiVersionOverrides: networking.k8s.io/v1
        enabled: true
        hosts:
        - name: chaos-mesh.local
      # https://chaos-mesh.org/docs/manage-user-permissions/#enable-or-disable-permission-authentication
      securityMode: false
