repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- chart: jetstack/cert-manager
  name: cert-manager
  namespace: cert-manager
  version: v1.18.1
  values:
  - values.yaml

- chart: jetstack/trust-manager
  name: trust-manager
  namespace: cert-manager
  version: v0.17.1
  set:
  - name: app.trust.namespace
    value: cert-manager
