repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - chart: jetstack/cert-manager
    name: cert-manager
    namespace: cert-manager
    version: v1.19.4
    values:
      - values.yaml
