repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - chart: jetstack/cert-manager
    name: cert-manager
    namespace: cert-manager
    version: v1.20.3
    values:
      - values.yaml

  - chart: ../../../charts/linkerd-tls-credentials
    name: linkerd-tls-credentials
    namespace: cert-manager
    values:
      - createTrustAnchor: true
