apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: admin
  namespace: {{ .Release.Namespace }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: {{ .Values.admin.repoURL }}
        revision: {{ .Values.admin.targetRevision }}
        files:
          - path: apps/*/*/appconfig.yaml
  template:
    metadata:
      name: {{ "'{{.path.basename}}'" }}
    spec:
      project: admin
      source:
        path: {{ "'{{.path.path}}'" }}
        repoURL: {{ .Values.admin.repoURL }}
        targetRevision: {{ .Values.admin.targetRevision }}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ "'{{index .path.segments 1}}'" }}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  templatePatch: |
    spec:
      {{ "{{- with .ignoreDifferences }}" }}
      ignoreDifferences:
        {{ "{{- toYaml . | nindent 8 }}" }}
      {{ "{{- end }}" }}
      syncPolicy:
        {{ "{{- if .syncPolicy.automated }}" }}
        automated: {}
        {{ "{{- end }}" }}
        {{ "{{- with .syncPolicy.managedNamespaceMetadata }}" }}
        managedNamespaceMetadata:
          {{ "{{- toYaml . | nindent 10 }}" }}
        {{ "{{- end }}" }}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
