repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argo-cd
    namespace: argo-cd
    createNamespace: true
    chart: argo/argo-cd
    version: 10.2.0
    values:
      - values.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: just
        args: ["patch-secret"]
      - events: ["postuninstall"]
        showlogs: true
        command: kubectl
        args: ["delete", "ns", "argo-cd"]

  - name: argo-cd-custom-resources
    namespace: argo-cd
    chart: ../../../charts/argo-cd-custom-resources
    needs: ["argo-cd/argo-cd"]
    values:
      - repoURL: https://github.com/mikutas/helmfiles
