patch-secret:
	kubectl patch secret -n argo-cd argocd-secret -p="{\"data\":{\"dex.github.clientID\": \"$CLIENT_ID\"}}"
	kubectl patch secret -n argo-cd argocd-secret -p="{\"data\":{\"dex.github.clientSecret\": \"$CLIENT_SECRET\"}}"
