{{- if .Values.enableCustomResources }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ .Chart.Name }}
  source:
    path: apps/{{ .Chart.Name }}
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/labels/helm.sh~1chart
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1cmd-params
        - /spec/template/metadata/annotations/checksum~1cm
        - /spec/template/metadata/annotations/checksum~1cmp-cm
        - /spec/template/metadata/labels/helm.sh~1chart
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1cmd-params
        - /spec/template/metadata/annotations/checksum~1cm
        - /spec/template/metadata/labels/helm.sh~1chart
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-projects
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ .Chart.Name }}
  source:
    path: apps/app-projects
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsets
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ .Chart.Name }}
  source:
    path: apps/appsets
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
{{- end }}
