ingresses: []
# - name: my-ingress
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#   className: ""
#   tls: []
#   #  - secretName: my-tls
#   #    hosts:
#   #      - example.local
#   rules:
#     - host: example.local
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: my-service
#                 port:
#                   number: 80
