on:
  workflow_call:
    inputs:
      changed-dir:
        required: true
        type: string
      artifact-dl-path:
        required: false
        type: string
        default: manifest

jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
      - name: get aqua.yaml
        run: |
          curl -LO https://raw.githubusercontent.com/mikutas/helmfiles/refs/heads/main/aqua.yaml
          cat aqua.yaml
          mv aqua.yaml ../

      - uses: mikutas/my-aqua-installer@main

      - run: mkdir ${{ inputs.artifact-dl-path }}

      - id: replace-slash
        run: |
          echo "name=$(echo ${{ inputs.changed-dir }} | sed 's/\//_/g')" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          name: ${{ steps.replace-slash.outputs.name }}
          path: ${{ inputs.artifact-dl-path }}

      - name: polaris audit
        run: |
          polaris audit -f pretty --audit-path ${{ inputs.artifact-dl-path }}
